/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.navids.soottutorial;

import dev.navids.soottutorial.visual.Visualizer;
import soot.*;
import soot.jimple.JimpleBody;
import soot.options.Options;
import soot.toolkits.graph.ClassicCompleteUnitGraph;
import soot.toolkits.graph.UnitGraph;

public class App {

    public static void setupSoot(){
        G.reset();
        Options.v().set_allow_phantom_refs(true);
        String sourcePath = System.getProperty("user.dir") + "/demo/one/";
        Options.v().set_soot_classpath(sourcePath);
        SootClass sc = Scene.v().loadClassAndSupport("A");
        sc.setApplicationClass();
        Scene.v().loadNecessaryClasses();

    }

    public static void main(String[] args) {
        setupSoot();
        SootClass mainClass = Scene.v().getSootClass("A");
        SootMethod sm = mainClass.getMethodByName("printFizzBuzz");
        JimpleBody body = (JimpleBody) sm.retrieveActiveBody();
        System.out.println("Method Signature: " + sm.getSignature() );
        System.out.println("--------------");
        System.out.println("Argument(s):");
        for(Local l : body.getParameterLocals()){
            System.out.println(l.getName() + " : " + l.getType());
        }
        System.out.println("--------------");
        System.out.println("This: " + body.getThisLocal());
        System.out.println("--------------");
        System.out.println("Units:");
        int c = 1;
        for(Unit u : body.getUnits()){
            System.out.println("("+c+") " +u.toString());
            c++;
        }
        System.out.println("--------------");
        UnitGraph ug = new ClassicCompleteUnitGraph(sm.getActiveBody());
        Visualizer.v().addUnitGraph(ug);
        Visualizer.v().draw();
        System.out.print("s");
    }
}
